# Generated by Django 3.2.12 on 2022-03-08 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_checkout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckOut',
        ),
    ]
