# Generated by Django 3.2.12 on 2022-03-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(max_length=100),
        ),
    ]
