# Generated by Django 3.2.12 on 2022-03-18 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20220318_0048'),
        ('store', '0015_auto_20220318_2022'),
    ]

    operations = [
    ]
