# Generated by Django 3.2.12 on 2022-03-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_merge_0015_auto_20220318_0048_0015_auto_20220318_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=14, verbose_name='order status'),
        ),
    ]
